service: sls-btc-tracker

provider:
  name: aws
  runtime: nodejs6.10
  region: prefered-region-name #for example eu-central-1 
  memorySize: 256
  timeout: 10
  role: arn-of-your-iam-role-with-dynamodb-access-here
  # IAM role arn
  environment:
    TABLE: table-name-here
    # your dynamodb table name here


functions:
  trackBtc:
    handler: scheduled/handler.trackBtc
    events:
        - schedule: rate(5 minutes)
