service: battle-lambda

provider:
  name: aws
  runtime: nodejs6.10
  region: prefered-region-name #for example eu-central-1 
  memorySize: 1024
  timeout: 5

functions:
  hello:
    handler: handler.handler
    events:
      - http:
         path: dumb
         method: get
